package com.example.finalproject.ui.theme

import androidx.compose.ui.graphics.Color

// 浅色主题
val Primary = Color(0xFF4A6FA5)
val OnPrimary = Color(0xFFFFFFFF)
val PrimaryContainer = Color(0xFFD6E4FF)
val OnPrimaryContainer = Color(0xFF001B3D)
val Secondary = Color(0xFF545F71)
val OnSecondary = Color(0xFFFFFFFF)
val SecondaryContainer = Color(0xFFD8E3F8)
val OnSecondaryContainer = Color(0xFF111C2B)
val Tertiary = Color(0xFF6D5677)
val OnTertiary = Color(0xFFFFFFFF)
val TertiaryContainer = Color(0xFFF6D9FF)
val OnTertiaryContainer = Color(0xFF261430)
val Error = Color(0xFFBA1A1A)
val ErrorContainer = Color(0xFFFFDAD6)
val OnError = Color(0xFFFFFFFF)
val OnErrorContainer = Color(0xFF410002)
val Background = Color(0xFFFDFCFF)
val OnBackground = Color(0xFF1A1C1E)
val Surface = Color(0xFFFDFCFF)
val OnSurface = Color(0xFF1A1C1E)
val SurfaceVariant = Color(0xFFDFE2EB)
val OnSurfaceVariant = Color(0xFF43474E)
val Outline = Color(0xFF73777F)

// 深色主题
val DarkPrimary = Color(0xFFAAC7FF)
val DarkOnPrimary = Color(0xFF002F65)
val DarkPrimaryContainer = Color(0xFF2E5280)
val DarkOnPrimaryContainer = Color(0xFFD6E4FF)
val DarkSecondary = Color(0xFFBCC7DC)
val DarkOnSecondary = Color(0xFF263141)
val DarkSecondaryContainer = Color(0xFF3C4858)
val DarkOnSecondaryContainer = Color(0xFFD8E3F8)
val DarkTertiary = Color(0xFFD9BDE4)
val DarkOnTertiary = Color(0xFF3D2847)
val DarkTertiaryContainer = Color(0xFF543F5E)
val DarkOnTertiaryContainer = Color(0xFFF6D9FF)
val DarkError = Color(0xFFFFB4AB)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnError = Color(0xFF690005)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF1A1C1E)
val DarkOnBackground = Color(0xFFE2E2E6)
val DarkSurface = Color(0xFF1A1C1E)
val DarkOnSurface = Color(0xFFE2E2E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C7CF)
val DarkOutline = Color(0xFF8D9199)
